👷 #15 optimize ci/cd

diff --git a/.github/workflows/lambda-pipeline.yml b/.github/workflows/lambda-pipeline.yml
--- a/.github/workflows/lambda-pipeline.yml
+++ b/.github/workflows/lambda-pipeline.yml
@@ -62,6 +62,26 @@ jobs:
       - name: Push Docker image
         run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/lambda-app:latest
 
+  test-with-curl:
+    runs-on: ubuntu-latest
+    needs: build-container
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Run Docker container
+        run: docker run -d -p 3001:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/lambda-app:latest
+      - name: Wait for container to be ready
+        run: sleep 10
+      - name: Test with curl
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST -H "Content-Type: application/json" -d '{"body": "{\"message\": \"Hello Lambda\"}"}' http://localhost:3001/2015-03-31/functions/function/invocations)
+          if [ "$response" -ne 200 ]; then
+            echo "Test failed with response code $response"
+            exit 1
+          fi
+      - name: Stop Docker container
+        run: docker stop $(docker ps -q --filter ancestor=${{ secrets.DOCKER_HUB_USERNAME }}/lambda-app:latest)
+
   deploy-to-kubernetes:
     runs-on: ubuntu-latest
     needs: build-container
@@ -79,12 +99,6 @@ jobs:
           k3d cluster create mycluster \
             --registry-create mycluster:5000 \
             -p 5432:5432@loadbalancer
-
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_TOKEN }}
 
       - name: Pull Docker image from Docker Hub
         run: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/lambda-app:latest
